### ISSUE TITLE
Does iOS API expose device button triggers or barcode?

### ISSUE THREAD

**Issue by jtrenton** [NordicID/nur_sample_ios#2]
Looking through the Android API, I can see that there's exposure to both trigger pulls as well as barcode reads. Does the iOS API expose these at all? That functionality is not in the demo app and thumbing through the framework, I don't see it either.

**Comment by jan-ekholm** [comment]
The barcode data and trigger data both come via the notification API. The Objective-C demo has the `ReadBarcodeViewController` class which reads barcodes and uses the trigger. Basically you want to implement the method:

`- (void) notificationReceived:(DWORD)timestamp type:(int)type data:(LPVOID)data length:(int)length`

from the `BluetoothDelegate` protocol. This is a minimal wrapper on top of the NurAPI function `NurApiSetNotificationCallback()`.

**Comment by jtrenton** [comment]
Thank you for responding. The trigger notification -- I was able to figure that out. The notificationReceived protocol method gets called every time I hold the trigger and every time I release the trigger with type of NUR_NOTIFICATION_IOCHANGE. That's cool. 

However, the barcode light does NOT come on when the trigger is pulled. And the trigger notification is the ONLY notification that calls the notificationReceived method. If I hold the trigger down, should I not expect to see the barcode light?

I have studied the Objective-C demo and I can see how you are handling barcode reads. It should be VERY easy to implement in Swift. But I'm just not GETTING the reads.

**Comment by jan-ekholm** [comment]
You must manually start the barcode reading, the trigger does not do that automatically. As you might perhaps want to do an RFID read instead. The way used in the demo to start reading a barcode is to call `NurAccReadBarcodeAsync()` which will give you a notification of type `NUR_NOTIFICATION_ACCESSORY` where the first byte of the data is `NUR_ACC_EVENT_BARCODE`. This is the code from the demo to handle the barcode:

```- (void) notificationReceived:(DWORD)timestamp type:(int)type data:(LPVOID)data length:(int)length {
    switch(type) {
        case NUR_NOTIFICATION_ACCESSORY: {
            BYTE *dataPtr = (BYTE*)data;
            BYTE evType = dataPtr[0];
            int status = NurApiGetLastNotificationStatus( [Bluetooth sharedInstance].nurapiHandle );
            if (evType == NUR_ACC_EVENT_BARCODE) {
                readingBarcode = NO;
                NurAccSetLedOpMode( [Bluetooth sharedInstance].nurapiHandle, NUR_ACC_LED_UNSET);

                if (status == NUR_SUCCESS) {
                    // create an ASCII string from the data after the type
                    NSString * barcode = [[NSString alloc] initWithBytes:data + 1 length:length - 1 encoding:NSASCIIStringEncoding];
                    // handle the barcode
                    ...
                }
                else if (status == NUR_ERROR_NOT_READY) {
                    // barcode reading cancelled
                    ignoreTrigger = YES;
                }
                else if ( status == NUR_ERROR_NO_TAG ) {
                    // no barcode found
                }
                else {
                    // an error of some sort in 'status'
                }
            }
        }
            break;
```

**Comment by jan-ekholm** [comment]
See:

``` 
/** @fn int NurAccReadBarcodeAsync(HANDLE hApi, WORD timeoutInMs)
 * Start asynchronous barcode reading operation in device.
 * Result will be reported via notification callback, NUR_NOTIFICATION_ACCESSORY with first byte set to NUR_ACC_EVENT_BARCODE.
 *
 * If barcode reading succeeded, notification status is set to NUR_SUCCESS (0) and barcode result is stored in notification data starting from byte index 1.
 * If barcode reading is cancelled, notification status is set to NUR_ERROR_NOT_READY (13).
 * If barcode reader is not present, notification status is set to NUR_ERROR_HW_MISMATCH (8).
 *
 * NOTE: While barcode reading is active, it is not allowed to send any other command than NurAccCancelBarcode() to device.
 * NOTE2: Pressing device trigger will cancel barcode reading automatically.
 *
 * @param	hApi			Handle to valid NurApi object instance.
 * @param	timeoutInMs		Reading timeout in milliseconds. Range 500 - 20000
 *
 * @return	Zero when succeeded, On error non-zero error code is returned.
 * @sa NurAccCancelBarcode(), NUR_NOTIFICATION_ACCESSORY, NUR_ACC_EVENT_BARCODE
 */
NUR_API
int NURAPICONV NurAccReadBarcodeAsync(HANDLE hApi, WORD timeoutInMs);
```

**Comment by jtrenton** [comment]
Things are looking good. I appreciate the help! I am getting NUR_SUCCESS when barcode reads. Only thing that I am getting stuck on now is the converting the following line to Swift:

`NSString * barcode = [[NSString alloc] initWithBytes:data + 1 length:length - 1 encoding:NSASCIIStringEncoding];`

**Comment by jan-ekholm** [comment]
This is from some Swift code that handles a barcode. Maybe not the best way to do things, as handling binary dats is a bit cumbersome, but it has been working ok.

``` 
    func notificationReceived(_ timestamp: DWORD, type: Int32, data: LPVOID!, length: Int32) {
        NSLog("received notification: \(type)")

        if type == Int32(NUR_NOTIFICATION_ACCESSORY.rawValue) {
            let dataPtr = UnsafeMutableRawPointer( data )
            guard let bytes = dataPtr?.bindMemory(to: Int8.self, capacity: Int(length) ) else {
                NSLog( "failed to convert byte data")
                return
            }

            let handle = Bluetooth.sharedInstance().nurapiHandle

            let eventType = bytes[0]

            if eventType == Int8(NUR_ACC_EVENT_BARCODE) {
                let status = NUR_ERRORCODES( UInt32(NurApiGetLastNotificationStatus( handle ) ))
                NurAccSetLedOpMode( handle, BYTE(NUR_ACC_LED_UNSET.rawValue));

                if status == NUR_SUCCESS {
                    NSLog( "read ok, bytes: \(length)" )

                    guard let stringDataPtr = dataPtr?.advanced(by: 1) else {
                        NSLog( "failed to convert byte data to string pointer")
                        return
                    }

                    guard let barcode = String(bytesNoCopy: stringDataPtr, length: length - 1, encoding: String.Encoding.ascii, freeWhenDone: false) else {
                        NSLog( "failed to convert byte data to string")
                        return
                    }
....
``` 

The exact string creation line is however deprecated, you should not handle string offsets like that in Swift  anymore, but you should get the idea.

**Comment by jtrenton** [comment]
This was very, very helpful. Thanks again for your time. For what it's worth, I ended up doing it like this:
`let length:Int = Int(length.advanced(by: -1))`
`let bytes = (data + 1).bindMemory(to: UInt8.self, capacity: length)`
`let buffer = UnsafeBufferPointer(start: bytes, count: length)`
`let rawBarcode = String(bytes: buffer, encoding: .ascii)`
`let barcode = rawBarcode!.components(separatedBy: "96S")[1]`

**Comment by jan-ekholm** [comment]
Great. :) There are several ways to handle raw binary data in Swift.
