### ISSUE TITLE
Library Files

### ISSUE THREAD

**Issue by milindsonone** [NordicID/nur_sample_ios#3]
Please specify which files are created for Demo purpose and which files we have to import to use NURAPI in iOS (Objective-C)

**Comment by jan-ekholm** [comment]
Basically you should only need the framework itself. All the other files in the Objective-C demo are extra. However, as the framework itself mainly handles the Bluetooth LE connectivity, you may find that some parts of the demo can be useful in your own application.

**Comment by milindsonone** [comment]
1. So we have to include the files which are under NurAPIBluetooth.Framework Folder?
2. And the same folder contains NurApiBluetooth without any extension that also we have to include?
If not then Framework folder doesn't contain .m files so if we invoke a method of an interface where is the implementation?

**Comment by jan-ekholm** [comment]
Just add the framework itself to your project in Xcode. Internally in the framework the public header files of NurAPI can be found as well as a library file (.a) that contains the actual implementation code. Take a look at how it's done in the demo.

**Comment by milindsonone** [comment]
Library File with .a extension is not present in git repo instead NurApiBluetooth without any extension is present which is creating an issue.
Can we add these libraries to Xamarin Solution?

**Comment by jan-ekholm** [comment]
That I do not know. Can you add other iOS frameworks? If so, this one should work just as well.

**Comment by milindsonone** [comment]
Unable to find Library file(.a) in https://github.com/NordicID/nur_sample_ios/tree/master/NurAPIBluetooth.framework
Please give some clarification

**Comment by jan-ekholm** [comment]
Pardon me, the file does not have a `.a` extension. It's the `NurAPIBluetooth` in the root of the framework.
