### ISSUE TITLE
Regularly getting NUR_ERROR_NOT_READY on barcode read

### ISSUE THREAD

**Issue by jtrenton** [NordicID/nur_sample_ios#4]
I'd say about 10-50% of the time, I get a NUR_ERROR_NOT_READY status during an asynchronous barcode operation. 

According to the documentation, the NUR_ERROR_NOT_READY status occurs when barcode reading is canceled. As you can see below, nowhere do I call NurAccCancelBarcode(). Nor do I push the trigger after the read has been initiated. 

How could the operation be getting cancelled? There shouldn't be any threading issues because everything that happens in the delegate functions are happening in the background asynchronously. 

The code below mirrors the relevant code found in the Obj-C Demo app pretty much note-for-note. And to your credit, the Obj-C Demo reads barcodes successfully 100% of the time. 

    class CreateViewController: UIViewController, BluetoothDelegate { 

    private var isReadingBarcode = false
    private var ignoreTrigger = false

    override func viewDidAppear(_ animated: Bool) {
        Bluetooth.sharedInstance().register(self)
        
        isReadingBarcode = false
        ignoreTrigger = false
    }

    func notificationReceived(_ timestamp: DWORD, type: Int32, data: LPVOID!, length: Int32) {
        switch NUR_NOTIFICATION(rawValue: UInt32(type)) {
        case NUR_NOTIFICATION_IOCHANGE:
            
            let dataPtr = data.bindMemory(to: NUR_IOCHANGE_DATA.self, capacity: Int(length))
            let iocData = dataPtr.pointee
            
            switch iocData.source {
            case NUR_ACC_TRIGGER_SOURCE:
                if iocData.dir == 0 {
                    if (!isReadingBarcode && !ignoreTrigger){
                        NSLog("Trigger pulled.")
                        NurAccSetLedOpMode(Bluetooth.sharedInstance().nurapiHandle, BYTE(NUR_ACC_LED_BLINK.rawValue));
                        let error = NurAccReadBarcodeAsync(Bluetooth.sharedInstance().nurapiHandle, 5000)
                        if (error == Int32(NUR_SUCCESS.rawValue)) {
                            isReadingBarcode = true
                            NSLog("CALL-SUCCESS: Call to async barcode function.")
                        }
                        else {
                            NSLog("CALL-FAILURE: Call to async barcode function. Error: \(error)")
                            NurAccSetLedOpMode(Bluetooth.sharedInstance().nurapiHandle, BYTE(NUR_ACC_LED_UNSET.rawValue))
                        }
                    }
                    
                    ignoreTrigger = false
                }
            default:
                print("")
            }
        case NUR_NOTIFICATION_ACCESSORY:
            
            let byte = data.bindMemory(to: UInt8.self, capacity: 1)
            let status = NurApiGetLastNotificationStatus(Bluetooth.sharedInstance().nurapiHandle);
            if byte.pointee == NUR_ACC_EVENT_BARCODE {
                
                NurAccSetLedOpMode(Bluetooth.sharedInstance().nurapiHandle, BYTE(NUR_ACC_LED_UNSET.rawValue))
                isReadingBarcode = false
                
                switch status {
                case UInt32(NUR_SUCCESS.rawValue):
                    NSLog("RECEIVED-SUCCESS: Received barcode notification.")
                    let length:Int = Int(length.advanced(by: -1))
                    let bytes = (data + 1).bindMemory(to: UInt8.self, capacity: length)
                    let buffer = UnsafeBufferPointer(start: bytes, count: length)
                    var rawBarcode = String(bytes: buffer, encoding: .ascii)
                    
                    if rawBarcode!.contains("96S"){
                        rawBarcode = rawBarcode!.components(separatedBy: "96S")[1]
                    }
                    rawBarcode = rawBarcode!.components(separatedBy: hexadecimalCharSet.inverted).joined()
                    
                case UInt32(NUR_ERROR_NOT_READY.rawValue):
                    ignoreTrigger = true
                    NSLog("RECEIVED-FAILURE: Received not ready error.")
                case UInt32(NUR_ERROR_HW_MISMATCH.rawValue):
                    NSLog("RECEIVED-FAILURE: Received HW mismatch error.")
                default:
                    NSLog("Recieved unknown status code.")
                }
                print("")
                
            }
        default:
            NSLog("received unknown notification: \(type)")
            break
        }
    }
}`

**Comment by jan-ekholm** [comment]
If your code (as you say) is more or less a verbatim copy of the demo, then there should not be any errors. I have never seen the reading in the demo get a `NUR_ERROR_NOT_READY`. You see no error logging from NurAPI prior to the error? Could it be that while you're reading the barcode you are also triggering some other operation?

**Comment by jtrenton** [comment]
My previous view controller was still making calls for battery info -- I forgot to invalidate the timer. Thanks for the pointer!

**Comment by gangireddi** [comment]
Not working as expected, when we turn off bluetooth in our device.
* If we made connection with scanner successfully and turn off bluetooth.Scanner is not connecting
